import { DocumentCategory, DocumentTemplate, FormField } from "@/constants/types";

const EXPEDITEUR_FIELDS: FormField[] = [
  {
    id: "expediteur_nom",
    label: "Prénom et nom",
    placeholder: "Camille Martin",
    required: true,
    section: "expediteur",
  },
  {
    id: "expediteur_adresse",
    label: "Adresse",
    placeholder: "14 rue des Lilas, 75015 Paris",
    required: true,
    section: "expediteur",
    multiline: true,
    type: "textarea",
  },
  {
    id: "expediteur_email",
    label: "Email",
    placeholder: "camille.martin@email.com",
    required: false,
    section: "expediteur",
    type: "email",
  },
  {
    id: "expediteur_tel",
    label: "Téléphone",
    placeholder: "06 12 34 56 78",
    required: false,
    section: "expediteur",
    type: "phone",
  },
];

const DESTINATAIRE_FIELDS: FormField[] = [
  {
    id: "destinataire_nom",
    label: "Nom du destinataire",
    placeholder: "Service client Orange",
    required: true,
    section: "destinataire",
  },
  {
    id: "destinataire_adresse",
    label: "Adresse du destinataire",
    placeholder: "Adresse complète du service",
    required: true,
    section: "destinataire",
    multiline: true,
    type: "textarea",
  },
];

const DATE_FIELDS: FormField[] = [
  {
    id: "lieu",
    label: "Lieu",
    placeholder: "Paris",
    required: true,
    section: "demande",
  },
  {
    id: "date",
    label: "Date du courrier",
    placeholder: "15 février 2026",
    required: true,
    section: "demande",
    type: "date",
  },
];

const DETAILS_FIELD: FormField = {
  id: "details",
  label: "Contexte détaillé",
  placeholder: "Précisez vos éléments factuels, références, montants, pièces...",
  required: false,
  section: "demande",
  multiline: true,
  type: "textarea",
};

const LETTER_BASE_FIELDS = [
  ...EXPEDITEUR_FIELDS,
  ...DESTINATAIRE_FIELDS,
  ...DATE_FIELDS,
  DETAILS_FIELD,
];

const CATEGORIES_V1: DocumentCategory[] = [
  {
    id: "resiliation",
    title: "Résiliation",
    icon: "scissors",
    color: "#F4B8AA",
    description: "Mettre fin à un contrat ou abonnement",
  },
  {
    id: "logement",
    title: "Logement",
    icon: "home",
    color: "#BFDFF7",
    description: "Bail, dépôt de garantie, voisinage",
  },
  {
    id: "travail",
    title: "Travail",
    icon: "briefcase",
    color: "#CDE9C8",
    description: "Démission, télétravail, congés",
  },
  {
    id: "administratif",
    title: "Administratif",
    icon: "file-text",
    color: "#F8DEB1",
    description: "Réclamations et demandes usuelles",
  },
  {
    id: "justice",
    title: "Justice",
    icon: "scale",
    color: "#E3CFF5",
    description: "Mises en demeure et plainte",
  },
  {
    id: "attestations",
    title: "Attestations",
    icon: "file-check",
    color: "#FAE9B7",
    description: "Attestations sur l'honneur fréquentes",
  },
  {
    id: "famille",
    title: "Famille",
    icon: "users",
    color: "#FFD3DF",
    description: "Autorisations parentales",
  },
  {
    id: "numerique",
    title: "Numérique / RGPD",
    icon: "shield",
    color: "#C7ECE2",
    description: "Exercice des droits sur les données",
  },
  {
    id: "finance",
    title: "Finance",
    icon: "wallet",
    color: "#D6E6FF",
    description: "Banque, assurances, paiements",
  },
  {
    id: "mobilite",
    title: "Mobilité",
    icon: "car",
    color: "#FFD9B8",
    description: "Transport, stationnement, déplacement",
  },
];

const TEMPLATES_V1: DocumentTemplate[] = [
  {
    id: "resil_telecom",
    version: "v1",
    title: "Résiliation forfait mobile / internet",
    categoryId: "resiliation",
    description: "Résilier un abonnement opérateur.",
    fields: [
      ...LETTER_BASE_FIELDS,
      {
        id: "reference_contrat",
        label: "N° de contrat / client",
        placeholder: "Contrat n° 123456789",
        required: true,
        section: "pieces",
      },
      {
        id: "date_effet",
        label: "Date d'effet souhaitée",
        placeholder: "Dès réception du courrier",
        required: false,
        section: "demande",
      },
    ],
    subject: "Résiliation de mon abonnement télécom - {{reference_contrat}}",
    opening: "Madame, Monsieur,",
    toneEnabled: true,
    paragraphs: [
      {
        text: "{{tone_opening}} vous notifier ma décision de résilier mon abonnement référencé ci-dessus.",
      },
      {
        text: "Je vous demande de prendre en compte cette résiliation à compter du {{date_effet}}.",
        includeIf: "date_effet",
      },
      {
        text: "Merci de me confirmer par écrit la date effective de résiliation, le solde de tout compte et les modalités de restitution du matériel le cas échéant.",
      },
      {
        text: "{{details}}",
        includeIf: "details",
      },
    ],
    closing: ["{{polite_formula}}"],
  },
  {
    id: "resil_assurance",
    version: "v1",
    title: "Résiliation assurance",
    categoryId: "resiliation",
    description: "Demande de résiliation de contrat d'assurance (auto/habitation/santé).",
    fields: [
      ...LETTER_BASE_FIELDS,
      {
        id: "type_assurance",
        label: "Type d'assurance",
        placeholder: "Assurance habitation",
        required: true,
        section: "demande",
      },
      {
        id: "reference_contrat",
        label: "Référence du contrat",
        placeholder: "Contrat n° HAB-458972",
        required: true,
        section: "pieces",
      },
      {
        id: "motif",
        label: "Motif de résiliation",
        placeholder: "Échéance annuelle / changement de situation",
        required: false,
        section: "demande",
      },
    ],
    subject: "Résiliation de mon contrat {{type_assurance}} - {{reference_contrat}}",
    opening: "Madame, Monsieur,",
    toneEnabled: true,
    paragraphs: [
      {
        text: "{{tone_opening}} vous informer de ma volonté de mettre fin à mon contrat {{type_assurance}} référencé {{reference_contrat}}.",
      },
      {
        text: "Cette demande est formulée au titre du motif suivant : {{motif}}.",
        includeIf: "motif",
      },
      {
        text: "Je vous prie de m'adresser un écrit confirmant la date de résiliation et, le cas échéant, le montant remboursé.",
      },
      { text: "{{details}}", includeIf: "details" },
    ],
    closing: ["{{polite_formula}}"],
  },
  {
    id: "resil_sport",
    version: "v1",
    title: "Résiliation salle de sport",
    categoryId: "resiliation",
    description: "Résiliation d'abonnement sportif.",
    fields: [
      ...LETTER_BASE_FIELDS,
      {
        id: "reference_abonnement",
        label: "Référence d'abonnement",
        placeholder: "Adhérent n° A-019283",
        required: true,
        section: "pieces",
      },
      {
        id: "date_effet",
        label: "Date d'effet demandée",
        placeholder: "À la prochaine échéance contractuelle",
        required: false,
        section: "demande",
      },
    ],
    subject: "Résiliation de mon abonnement de salle de sport",
    opening: "Madame, Monsieur,",
    toneEnabled: true,
    paragraphs: [
      {
        text: "{{tone_opening}} vous demander la résiliation de mon abonnement n° {{reference_abonnement}}.",
      },
      {
        text: "Je vous remercie de faire produire effet à cette résiliation à compter du {{date_effet}}.",
        includeIf: "date_effet",
      },
      {
        text: "Je vous prie de me confirmer par écrit la bonne prise en compte de cette demande.",
      },
      { text: "{{details}}", includeIf: "details" },
    ],
    closing: ["{{polite_formula}}"],
  },
  {
    id: "resil_saas",
    version: "v1",
    title: "Résiliation service en ligne",
    categoryId: "resiliation",
    description: "Mettre fin à un abonnement numérique.",
    fields: [
      ...LETTER_BASE_FIELDS,
      {
        id: "service_nom",
        label: "Nom du service",
        placeholder: "Plateforme XYZ",
        required: true,
        section: "demande",
      },
      {
        id: "reference_compte",
        label: "Référence compte",
        placeholder: "Compte utilisateur 84572",
        required: true,
        section: "pieces",
      },
    ],
    subject: "Résiliation de mon abonnement {{service_nom}}",
    opening: "Madame, Monsieur,",
    toneEnabled: true,
    paragraphs: [
      {
        text: "{{tone_opening}} vous notifier la résiliation de mon abonnement au service {{service_nom}}, rattaché au compte {{reference_compte}}.",
      },
      {
        text: "Je vous demande de cesser tout prélèvement à compter de la date de prise d'effet de cette résiliation.",
      },
      { text: "{{details}}", includeIf: "details" },
    ],
    closing: ["{{polite_formula}}"],
  },
  {
    id: "logt_conge_locataire",
    version: "v1",
    title: "Congé donné par le locataire",
    categoryId: "logement",
    description: "Informer le bailleur de votre départ et du préavis.",
    fields: [
      ...LETTER_BASE_FIELDS,
      {
        id: "adresse_logement",
        label: "Adresse du logement loué",
        placeholder: "22 avenue de la République, 33000 Bordeaux",
        required: true,
        section: "demande",
      },
      {
        id: "duree_preavis",
        label: "Durée du préavis",
        placeholder: "1 mois",
        required: true,
        section: "demande",
      },
      {
        id: "date_depart",
        label: "Date prévisionnelle de départ",
        placeholder: "30 avril 2026",
        required: false,
        section: "demande",
      },
    ],
    subject: "Congé du locataire - logement situé {{adresse_logement}}",
    opening: "Madame, Monsieur,",
    toneEnabled: true,
    paragraphs: [
      {
        text: "{{tone_opening}} vous notifier mon congé concernant le logement situé {{adresse_logement}}.",
      },
      {
        text: "Conformément à la réglementation en vigueur, le préavis applicable est de {{duree_preavis}} à compter de la réception de ce courrier.",
      },
      {
        text: "Ma date de départ prévisionnelle est fixée au {{date_depart}}.",
        includeIf: "date_depart",
      },
      {
        text: "Je reste à votre disposition pour convenir des modalités de l'état des lieux de sortie.",
      },
      { text: "{{details}}", includeIf: "details" },
    ],
    closing: ["{{polite_formula}}"],
  },
  {
    id: "logt_depot_garantie",
    version: "v1",
    title: "Remboursement dépôt de garantie",
    categoryId: "logement",
    description: "Relancer un bailleur pour la restitution du dépôt de garantie.",
    fields: [
      ...LETTER_BASE_FIELDS,
      {
        id: "adresse_logement",
        label: "Adresse du logement",
        placeholder: "22 avenue de la République, 33000 Bordeaux",
        required: true,
        section: "demande",
      },
      {
        id: "montant_depot",
        label: "Montant du dépôt de garantie",
        placeholder: "850 EUR",
        required: true,
        section: "pieces",
      },
      {
        id: "date_sortie",
        label: "Date d'état des lieux de sortie",
        placeholder: "3 janvier 2026",
        required: true,
        section: "pieces",
      },
      {
        id: "iban",
        label: "IBAN pour remboursement",
        placeholder: "FR76 XXXX XXXX XXXX XXXX XXXX XXX",
        required: false,
        section: "pieces",
      },
    ],
    subject: "Demande de restitution du dépôt de garantie",
    opening: "Madame, Monsieur,",
    toneEnabled: true,
    paragraphs: [
      {
        text: "{{tone_opening}} vous demander la restitution de mon dépôt de garantie d'un montant de {{montant_depot}}, relatif au logement {{adresse_logement}}.",
      },
      {
        text: "L'état des lieux de sortie a été réalisé le {{date_sortie}}.",
      },
      {
        text: "Je vous remercie de procéder au remboursement dans les délais légaux. Vous pouvez effectuer le virement sur l'IBAN suivant : {{iban}}.",
        includeIf: "iban",
      },
      {
        text: "À défaut de régularisation rapide, je me réserve la possibilité d'engager les démarches nécessaires.",
      },
      { text: "{{details}}", includeIf: "details" },
    ],
    closing: ["{{polite_formula}}"],
  },
  {
    id: "logt_nuisances",
    version: "v1",
    title: "Mise en demeure de cesser les nuisances",
    categoryId: "logement",
    description: "Courrier de mise en demeure pour nuisances sonores de voisinage.",
    fields: [
      ...LETTER_BASE_FIELDS,
      {
        id: "nature_nuisance",
        label: "Nature des nuisances",
        placeholder: "Musique amplifiée répétée après 23h",
        required: true,
        section: "demande",
      },
      {
        id: "periode_nuisance",
        label: "Période concernée",
        placeholder: "Depuis novembre 2025",
        required: true,
        section: "demande",
      },
    ],
    subject: "Mise en demeure de faire cesser les nuisances de voisinage",
    opening: "Madame, Monsieur,",
    toneEnabled: true,
    paragraphs: [
      {
        text: "{{tone_opening}} vous demander de faire cesser les nuisances suivantes : {{nature_nuisance}}.",
      },
      {
        text: "Ces troubles durent {{periode_nuisance}} et perturbent gravement ma jouissance paisible du logement.",
      },
      {
        text: "Je vous mets en demeure de prendre immédiatement les mesures nécessaires pour mettre fin à cette situation.",
      },
      {
        text: "Sans amélioration rapide, je serai contraint(e) de saisir les autorités compétentes.",
      },
      { text: "{{details}}", includeIf: "details" },
    ],
    closing: ["{{polite_formula}}"],
  },
  {
    id: "logt_cautionnement",
    version: "v1",
    title: "Acte de cautionnement (bail)",
    categoryId: "logement",
    description: "Modèle d'engagement de caution pour location d'habitation.",
    fields: [
      ...EXPEDITEUR_FIELDS,
      ...DATE_FIELDS,
      {
        id: "locataire_nom",
        label: "Nom du locataire",
        placeholder: "Nina Dupuis",
        required: true,
        section: "demande",
      },
      {
        id: "bailleur_nom",
        label: "Nom du bailleur",
        placeholder: "M. Pierre Laurent",
        required: true,
        section: "demande",
      },
      {
        id: "adresse_logement",
        label: "Adresse du logement",
        placeholder: "8 rue Victor-Hugo, 69002 Lyon",
        required: true,
        section: "demande",
      },
      {
        id: "montant_loyer",
        label: "Montant mensuel du loyer + charges",
        placeholder: "1 050 EUR",
        required: true,
        section: "pieces",
      },
      {
        id: "duree_engagement",
        label: "Durée de l'engagement",
        placeholder: "3 ans",
        required: true,
        section: "pieces",
      },
    ],
    subject: "Acte de cautionnement solidaire",
    headerMode: "simple",
    paragraphs: [
      {
        text: "Je soussigné(e) {{expediteur_nom}}, demeurant {{expediteur_adresse}}, me porte caution solidaire de {{locataire_nom}} au profit de {{bailleur_nom}} pour le logement situé {{adresse_logement}}.",
      },
      {
        text: "Je reconnais avoir pris connaissance de la nature et de l'étendue de mon engagement, couvrant notamment les loyers, charges et éventuels frais liés à l'exécution du bail.",
      },
      {
        text: "Le montant de référence du loyer et des charges est de {{montant_loyer}} par mois.",
      },
      {
        text: "Le présent cautionnement est souscrit pour une durée de {{duree_engagement}}.",
      },
      {
        text: "Fait pour servir et valoir ce que de droit.",
      },
    ],
    footer: ["Fait à {{lieu}}, le {{date}}.", "Signature de la caution : {{expediteur_nom}}"],
  },
  {
    id: "rh_demission",
    version: "v1",
    title: "Lettre de démission",
    categoryId: "travail",
    description: "Notifier sa démission à l'employeur.",
    fields: [
      ...LETTER_BASE_FIELDS,
      {
        id: "poste",
        label: "Poste occupé",
        placeholder: "Chef de projet",
        required: true,
        section: "demande",
      },
      {
        id: "date_debut_preavis",
        label: "Date de début du préavis",
        placeholder: "À réception du courrier",
        required: false,
        section: "demande",
      },
      {
        id: "date_fin_preavis",
        label: "Date de fin de préavis estimée",
        placeholder: "30 avril 2026",
        required: false,
        section: "demande",
      },
    ],
    subject: "Démission de mon poste de {{poste}}",
    opening: "Madame, Monsieur,",
    toneEnabled: true,
    paragraphs: [
      {
        text: "{{tone_opening}} vous présenter ma démission du poste de {{poste}}.",
      },
      {
        text: "Conformément à mes obligations contractuelles, mon préavis débutera {{date_debut_preavis}}.",
        includeIf: "date_debut_preavis",
      },
      {
        text: "La fin prévisionnelle de mon contrat est fixée au {{date_fin_preavis}}.",
        includeIf: "date_fin_preavis",
      },
      {
        text: "Je reste mobilisé(e) pour organiser une passation structurée de mes dossiers.",
      },
      { text: "{{details}}", includeIf: "details" },
    ],
    closing: ["{{polite_formula}}"],
  },
  {
    id: "rh_conge_parental",
    version: "v1",
    title: "Demande de congé parental",
    categoryId: "travail",
    description: "Demande de congé parental d'éducation (privé/fonction publique).",
    fields: [
      ...LETTER_BASE_FIELDS,
      {
        id: "date_debut",
        label: "Date de début du congé",
        placeholder: "1er juin 2026",
        required: true,
        section: "demande",
      },
      {
        id: "duree_conge",
        label: "Durée demandée",
        placeholder: "6 mois",
        required: true,
        section: "demande",
      },
      {
        id: "temps_partiel",
        label: "Organisation (facultatif)",
        placeholder: "Congé à temps plein / temps partiel 80%",
        required: false,
        section: "demande",
      },
    ],
    subject: "Demande de congé parental d'éducation",
    opening: "Madame, Monsieur,",
    toneEnabled: true,
    paragraphs: [
      {
        text: "{{tone_opening}} solliciter un congé parental d'éducation à compter du {{date_debut}} pour une durée de {{duree_conge}}.",
      },
      {
        text: "Organisation souhaitée : {{temps_partiel}}.",
        includeIf: "temps_partiel",
      },
      {
        text: "Je vous remercie de bien vouloir me confirmer la prise en compte de cette demande.",
      },
      { text: "{{details}}", includeIf: "details" },
    ],
    closing: ["{{polite_formula}}"],
  },
  {
    id: "rh_teletravail",
    version: "v1",
    title: "Demande de télétravail",
    categoryId: "travail",
    description: "Proposer un cadre de télétravail avec organisation claire.",
    fields: [
      ...LETTER_BASE_FIELDS,
      {
        id: "poste",
        label: "Poste",
        placeholder: "Product designer",
        required: true,
        section: "demande",
      },
      {
        id: "rythme",
        label: "Rythme souhaité",
        placeholder: "2 jours par semaine",
        required: true,
        section: "demande",
      },
    ],
    subject: "Demande de télétravail",
    opening: "Madame, Monsieur,",
    toneEnabled: true,
    paragraphs: [
      {
        text: "{{tone_opening}} solliciter la mise en place du télétravail pour mes fonctions de {{poste}}.",
      },
      {
        text: "Le rythme proposé est de {{rythme}}, avec maintien de la continuité de service et des objectifs.",
      },
      {
        text: "Je suis disponible pour convenir des modalités opérationnelles (outillage, plages horaires, reporting).",
      },
      { text: "{{details}}", includeIf: "details" },
    ],
    closing: ["{{polite_formula}}"],
  },
  {
    id: "rh_periode_essai",
    version: "v1",
    title: "Rupture de période d'essai",
    categoryId: "travail",
    description: "Notifier la rupture de la période d'essai.",
    fields: [
      ...LETTER_BASE_FIELDS,
      {
        id: "poste",
        label: "Poste concerné",
        placeholder: "Ingénieur logiciel",
        required: true,
        section: "demande",
      },
      {
        id: "date_effet",
        label: "Date d'effet",
        placeholder: "31 mars 2026",
        required: true,
        section: "demande",
      },
    ],
    subject: "Rupture de la période d'essai",
    opening: "Madame, Monsieur,",
    toneEnabled: true,
    paragraphs: [
      {
        text: "{{tone_opening}} vous notifier la rupture de ma période d'essai au poste de {{poste}}.",
      },
      {
        text: "Cette rupture prendra effet le {{date_effet}}, dans le respect du délai de prévenance applicable.",
      },
      { text: "{{details}}", includeIf: "details" },
    ],
    closing: ["{{polite_formula}}"],
  },
  {
    id: "adm_contestation_facture",
    version: "v1",
    title: "Contestation de facture",
    categoryId: "administratif",
    description: "Contester une facture et demander rectification.",
    fields: [
      ...LETTER_BASE_FIELDS,
      {
        id: "numero_facture",
        label: "Numéro de facture",
        placeholder: "FAC-2026-00482",
        required: true,
        section: "pieces",
      },
      {
        id: "montant_facture",
        label: "Montant contesté",
        placeholder: "219 EUR",
        required: true,
        section: "pieces",
      },
      {
        id: "motif",
        label: "Motif de contestation",
        placeholder: "Prestations non réalisées",
        required: true,
        section: "demande",
      },
    ],
    subject: "Contestation de la facture {{numero_facture}}",
    opening: "Madame, Monsieur,",
    toneEnabled: true,
    paragraphs: [
      {
        text: "{{tone_opening}} contester la facture {{numero_facture}} d'un montant de {{montant_facture}}.",
      },
      {
        text: "Le motif de contestation est le suivant : {{motif}}.",
      },
      {
        text: "Je vous demande de vérifier votre facturation et de me transmettre un document rectificatif.",
      },
      { text: "{{details}}", includeIf: "details" },
    ],
    closing: ["{{polite_formula}}"],
  },
  {
    id: "adm_remboursement",
    version: "v1",
    title: "Demande de remboursement",
    categoryId: "administratif",
    description: "Demander le remboursement d'un paiement indu.",
    fields: [
      ...LETTER_BASE_FIELDS,
      {
        id: "motif",
        label: "Motif",
        placeholder: "Paiement en double",
        required: true,
        section: "demande",
      },
      {
        id: "montant",
        label: "Montant demandé",
        placeholder: "72 EUR",
        required: true,
        section: "pieces",
      },
      {
        id: "reference_operation",
        label: "Référence opération",
        placeholder: "Transaction 998214",
        required: false,
        section: "pieces",
      },
    ],
    subject: "Demande de remboursement - {{montant}}",
    opening: "Madame, Monsieur,",
    toneEnabled: true,
    paragraphs: [
      {
        text: "{{tone_opening}} solliciter le remboursement de la somme de {{montant}}, versée au titre de {{motif}}.",
      },
      {
        text: "Référence de l'opération : {{reference_operation}}.",
        includeIf: "reference_operation",
      },
      {
        text: "Je vous remercie de procéder au remboursement dans les meilleurs délais.",
      },
      { text: "{{details}}", includeIf: "details" },
    ],
    closing: ["{{polite_formula}}"],
  },
  {
    id: "adm_delai_paiement",
    version: "v1",
    title: "Demande de délai de paiement",
    categoryId: "administratif",
    description: "Demander un échéancier amiable.",
    fields: [
      ...LETTER_BASE_FIELDS,
      {
        id: "montant",
        label: "Montant dû",
        placeholder: "1 280 EUR",
        required: true,
        section: "pieces",
      },
      {
        id: "proposition",
        label: "Proposition d'échéancier",
        placeholder: "4 mensualités de 320 EUR",
        required: true,
        section: "demande",
      },
    ],
    subject: "Demande de délai de paiement",
    opening: "Madame, Monsieur,",
    toneEnabled: true,
    paragraphs: [
      {
        text: "{{tone_opening}} solliciter un délai de paiement pour la somme de {{montant}}.",
      },
      {
        text: "Je vous propose l'échéancier suivant : {{proposition}}.",
      },
      {
        text: "Cette demande vise à régulariser la situation de manière sérieuse et soutenable.",
      },
      { text: "{{details}}", includeIf: "details" },
    ],
    closing: ["{{polite_formula}}"],
  },
  {
    id: "adm_refus_devis",
    version: "v1",
    title: "Refus de devis",
    categoryId: "administratif",
    description: "Notifier un refus de devis de manière formelle.",
    fields: [
      ...LETTER_BASE_FIELDS,
      {
        id: "reference_devis",
        label: "Référence devis",
        placeholder: "DEV-7426",
        required: true,
        section: "pieces",
      },
    ],
    subject: "Refus du devis {{reference_devis}}",
    opening: "Madame, Monsieur,",
    toneEnabled: true,
    paragraphs: [
      {
        text: "Je vous remercie pour le devis {{reference_devis}} transmis.",
      },
      {
        text: "Après analyse, {{tone_opening}} vous informer que je ne souhaite pas y donner suite.",
      },
      { text: "{{details}}", includeIf: "details" },
    ],
    closing: ["{{polite_formula}}"],
  },
  {
    id: "jud_mise_en_demeure_paiement",
    version: "v1",
    title: "Mise en demeure de paiement",
    categoryId: "justice",
    description: "Dernière relance avant action judiciaire.",
    fields: [
      ...LETTER_BASE_FIELDS,
      {
        id: "montant",
        label: "Montant dû",
        placeholder: "2 450 EUR",
        required: true,
        section: "pieces",
      },
      {
        id: "origine_creance",
        label: "Origine de la créance",
        placeholder: "Facture FAC-2026-018",
        required: true,
        section: "demande",
      },
      {
        id: "delai",
        label: "Délai accordé (jours)",
        placeholder: "8",
        required: true,
        section: "demande",
        type: "number",
      },
    ],
    subject: "Mise en demeure de paiement",
    opening: "Madame, Monsieur,",
    toneEnabled: true,
    paragraphs: [
      {
        text: "Malgré plusieurs relances, la somme de {{montant}} au titre de {{origine_creance}} demeure impayée.",
      },
      {
        text: "Par la présente, {{tone_opening}} procéder au règlement complet sous {{delai}} jours à compter de la réception de ce courrier.",
      },
      {
        text: "À défaut, je me réserve le droit d'engager toute procédure utile devant la juridiction compétente.",
      },
      { text: "{{details}}", includeIf: "details" },
    ],
    closing: ["{{polite_formula}}"],
  },
  {
    id: "jud_mise_en_demeure_livraison",
    version: "v1",
    title: "Mise en demeure de livraison",
    categoryId: "justice",
    description: "Exiger la livraison ou le remboursement.",
    fields: [
      ...LETTER_BASE_FIELDS,
      {
        id: "reference_commande",
        label: "Référence commande",
        placeholder: "CMD-2026-921",
        required: true,
        section: "pieces",
      },
      {
        id: "date_commande",
        label: "Date de commande",
        placeholder: "12 janvier 2026",
        required: true,
        section: "pieces",
      },
      {
        id: "delai",
        label: "Délai accordé (jours)",
        placeholder: "8",
        required: true,
        section: "demande",
        type: "number",
      },
    ],
    subject: "Mise en demeure de livraison - commande {{reference_commande}}",
    opening: "Madame, Monsieur,",
    toneEnabled: true,
    paragraphs: [
      {
        text: "Je constate que la commande {{reference_commande}}, passée le {{date_commande}}, n'a pas été livrée dans les délais annoncés.",
      },
      {
        text: "{{tone_opening}} exécuter la livraison sous {{delai}} jours à compter de la réception du présent courrier.",
      },
      {
        text: "À défaut, je demanderai la résolution de la commande et le remboursement intégral des sommes versées.",
      },
      { text: "{{details}}", includeIf: "details" },
    ],
    closing: ["{{polite_formula}}"],
  },
  {
    id: "jud_plainte_procureur",
    version: "v1",
    title: "Plainte au procureur de la République",
    categoryId: "justice",
    description: "Signaler des faits pénaux au parquet.",
    fields: [
      ...LETTER_BASE_FIELDS,
      {
        id: "faits",
        label: "Exposé synthétique des faits",
        placeholder: "Fraude au faux support technique avec paiement contraint",
        required: true,
        section: "demande",
        multiline: true,
        type: "textarea",
      },
      {
        id: "date_faits",
        label: "Date des faits",
        placeholder: "28 janvier 2026",
        required: true,
        section: "pieces",
      },
      {
        id: "lieu_faits",
        label: "Lieu des faits",
        placeholder: "Lyon / en ligne",
        required: true,
        section: "pieces",
      },
      {
        id: "auteurs",
        label: "Personne(s) mise(s) en cause",
        placeholder: "Identité connue ou inconnue",
        required: false,
        section: "pieces",
      },
    ],
    subject: "Plainte auprès de Monsieur/Madame le Procureur de la République",
    opening: "Monsieur le Procureur, Madame la Procureure,",
    headerMode: "letter",
    toneEnabled: false,
    paragraphs: [
      {
        text: "Je soussigné(e) {{expediteur_nom}}, demeurant {{expediteur_adresse}}, porte plainte pour les faits suivants : {{faits}}.",
      },
      {
        text: "Ces faits se sont produits le {{date_faits}} à {{lieu_faits}}.",
      },
      {
        text: "Personne(s) visée(s) : {{auteurs}}.",
        includeIf: "auteurs",
      },
      {
        text: "Je joins les éléments utiles en ma possession et reste à la disposition des services d'enquête.",
      },
      { text: "{{details}}", includeIf: "details" },
    ],
    closing: [
      "Je vous prie d'agréer, Monsieur le Procureur, Madame la Procureure, l'expression de ma considération distinguée.",
    ],
  },
  {
    id: "att_honneur",
    version: "v1",
    title: "Attestation sur l'honneur",
    categoryId: "attestations",
    description: "Déclaration sur l'honneur polyvalente.",
    headerMode: "simple",
    toneEnabled: false,
    fields: [
      ...EXPEDITEUR_FIELDS,
      ...DATE_FIELDS,
      {
        id: "declaration",
        label: "Déclaration",
        placeholder: "Je certifie sur l'honneur que...",
        required: true,
        section: "demande",
        multiline: true,
        type: "textarea",
      },
    ],
    subject: "Attestation sur l'honneur",
    paragraphs: [
      {
        text: "Je soussigné(e) {{expediteur_nom}}, demeurant {{expediteur_adresse}}, atteste sur l'honneur que :",
      },
      {
        text: "{{declaration}}",
      },
      {
        text: "Cette attestation est établie pour servir et valoir ce que de droit.",
      },
    ],
    footer: ["Fait à {{lieu}}, le {{date}}.", "Signature : {{expediteur_nom}}"],
  },
  {
    id: "att_hebergement",
    version: "v1",
    title: "Attestation d'hébergement",
    categoryId: "attestations",
    description: "Attester qu'une personne est hébergée à votre domicile.",
    headerMode: "simple",
    toneEnabled: false,
    fields: [
      ...EXPEDITEUR_FIELDS,
      ...DATE_FIELDS,
      {
        id: "personne_hebergee",
        label: "Personne hébergée",
        placeholder: "Alexandre Robert",
        required: true,
        section: "demande",
      },
      {
        id: "date_debut_hebergement",
        label: "Date de début de l'hébergement",
        placeholder: "Depuis le 4 septembre 2025",
        required: false,
        section: "demande",
      },
    ],
    subject: "Attestation d'hébergement",
    paragraphs: [
      {
        text: "Je soussigné(e) {{expediteur_nom}}, atteste héberger à mon domicile {{personne_hebergee}} à l'adresse {{expediteur_adresse}}.",
      },
      {
        text: "Cet hébergement est effectif {{date_debut_hebergement}}.",
        includeIf: "date_debut_hebergement",
      },
      {
        text: "Cette attestation est établie pour servir et valoir ce que de droit.",
      },
    ],
    footer: ["Fait à {{lieu}}, le {{date}}.", "Signature : {{expediteur_nom}}"],
  },
  {
    id: "att_domicile",
    version: "v1",
    title: "Attestation de domicile",
    categoryId: "attestations",
    description: "Certifier son adresse de résidence actuelle.",
    headerMode: "simple",
    toneEnabled: false,
    fields: [
      ...EXPEDITEUR_FIELDS,
      ...DATE_FIELDS,
      {
        id: "adresse_domicile",
        label: "Adresse du domicile",
        placeholder: "14 rue des Lilas, 75015 Paris",
        required: true,
        section: "demande",
      },
    ],
    subject: "Attestation de domicile",
    paragraphs: [
      {
        text: "Je soussigné(e) {{expediteur_nom}}, atteste résider à l'adresse suivante : {{adresse_domicile}}.",
      },
      {
        text: "La présente est délivrée pour servir et valoir ce que de droit.",
      },
    ],
    footer: ["Fait à {{lieu}}, le {{date}}.", "Signature : {{expediteur_nom}}"],
  },
  {
    id: "fam_autorisation_travail_mineur",
    version: "v1",
    title: "Autorisation parentale de travail (mineur)",
    categoryId: "famille",
    description: "Autoriser son enfant mineur à travailler pendant les vacances.",
    fields: [
      ...LETTER_BASE_FIELDS,
      {
        id: "enfant_nom",
        label: "Nom de l'enfant",
        placeholder: "Léo Martin",
        required: true,
        section: "demande",
      },
      {
        id: "enfant_naissance",
        label: "Date de naissance de l'enfant",
        placeholder: "12 août 2010",
        required: true,
        section: "demande",
      },
      {
        id: "poste",
        label: "Emploi visé",
        placeholder: "Employé polyvalent",
        required: true,
        section: "demande",
      },
      {
        id: "periode",
        label: "Période de travail",
        placeholder: "du 7 juillet au 1er août 2026",
        required: true,
        section: "demande",
      },
    ],
    subject: "Autorisation parentale de travail d'un mineur",
    opening: "Madame, Monsieur,",
    toneEnabled: false,
    paragraphs: [
      {
        text: "Je soussigné(e) {{expediteur_nom}}, représentant(e) légal(e) de {{enfant_nom}}, né(e) le {{enfant_naissance}}, autorise mon enfant à exercer l'emploi de {{poste}} sur la période {{periode}}.",
      },
      {
        text: "Je confirme que cette autorisation est donnée librement et dans le respect des règles applicables au travail des mineurs.",
      },
      { text: "{{details}}", includeIf: "details" },
    ],
    closing: [
      "Je vous prie d'agréer, Madame, Monsieur, l'expression de mes salutations distinguées.",
    ],
  },
  {
    id: "fam_autorisation_sortie",
    version: "v1",
    title: "Autorisation parentale de sortie",
    categoryId: "famille",
    description: "Autoriser un déplacement d'enfant mineur.",
    headerMode: "simple",
    toneEnabled: false,
    fields: [
      ...EXPEDITEUR_FIELDS,
      ...DATE_FIELDS,
      DETAILS_FIELD,
      {
        id: "enfant_nom",
        label: "Nom de l'enfant",
        placeholder: "Léa Martin",
        required: true,
        section: "demande",
      },
      {
        id: "enfant_naissance",
        label: "Date de naissance",
        placeholder: "4 janvier 2011",
        required: true,
        section: "demande",
      },
      {
        id: "accompagnant",
        label: "Nom de l'accompagnant",
        placeholder: "Sophie Martin",
        required: true,
        section: "demande",
      },
      {
        id: "destination",
        label: "Destination",
        placeholder: "Espagne",
        required: true,
        section: "demande",
      },
      {
        id: "periode",
        label: "Période",
        placeholder: "du 10 avril au 17 avril 2026",
        required: true,
        section: "demande",
      },
    ],
    subject: "Autorisation parentale de sortie",
    paragraphs: [
      {
        text: "Je soussigné(e) {{expediteur_nom}}, parent/tuteur légal de {{enfant_nom}} né(e) le {{enfant_naissance}}, autorise mon enfant à voyager vers {{destination}} pendant {{periode}}, accompagné(e) de {{accompagnant}}.",
      },
      {
        text: "La présente autorisation est délivrée pour justifier de mon accord parental.",
      },
      { text: "{{details}}", includeIf: "details" },
    ],
    footer: ["Fait à {{lieu}}, le {{date}}.", "Signature : {{expediteur_nom}}"],
  },
  {
    id: "rgpd_droit_acces",
    version: "v1",
    title: "Exercice du droit d'accès (RGPD)",
    categoryId: "numerique",
    description: "Demander l'accès à ses données personnelles.",
    fields: [
      ...LETTER_BASE_FIELDS,
      {
        id: "service_concerne",
        label: "Service ou compte concerné",
        placeholder: "Compte client n° 99821",
        required: true,
        section: "pieces",
      },
      {
        id: "identifiants",
        label: "Identifiant(s) utiles",
        placeholder: "Email de connexion, ID client...",
        required: false,
        section: "pieces",
      },
    ],
    subject: "Exercice de mon droit d'accès à mes données personnelles",
    opening: "Madame, Monsieur,",
    toneEnabled: false,
    paragraphs: [
      {
        text: "Par la présente, je souhaite exercer mon droit d'accès, conformément au RGPD, concernant les données personnelles me concernant au titre du service {{service_concerne}}.",
      },
      {
        text: "Identifiants utiles pour traiter ma demande : {{identifiants}}.",
        includeIf: "identifiants",
      },
      {
        text: "Je vous remercie de me communiquer une copie des données ainsi que les informations relatives à leur traitement.",
      },
      { text: "{{details}}", includeIf: "details" },
    ],
    closing: [
      "Je vous prie d'agréer, Madame, Monsieur, l'expression de mes salutations distinguées.",
    ],
  },
  {
    id: "rgpd_effacement",
    version: "v1",
    title: "Demande d'effacement des données",
    categoryId: "numerique",
    description: "Demander la suppression de données personnelles.",
    fields: [
      ...LETTER_BASE_FIELDS,
      {
        id: "service_concerne",
        label: "Service concerné",
        placeholder: "Plateforme ABC",
        required: true,
        section: "pieces",
      },
      {
        id: "motif",
        label: "Motif de la demande",
        placeholder: "Données non nécessaires / retrait du consentement",
        required: true,
        section: "demande",
      },
    ],
    subject: "Exercice de mon droit à l'effacement de mes données personnelles",
    opening: "Madame, Monsieur,",
    toneEnabled: false,
    paragraphs: [
      {
        text: "Je vous demande de procéder à l'effacement de mes données personnelles relatives au service {{service_concerne}}.",
      },
      {
        text: "Cette demande est fondée sur le motif suivant : {{motif}}.",
      },
      {
        text: "Merci de me confirmer par écrit la suppression effective ou de motiver un éventuel refus.",
      },
      { text: "{{details}}", includeIf: "details" },
    ],
    closing: [
      "Je vous prie d'agréer, Madame, Monsieur, l'expression de mes salutations distinguées.",
    ],
  },
];

const EXTRA_TEMPLATES_V1: DocumentTemplate[] = [
  {
    id: "resil_energie",
    version: "v1",
    title: "Résiliation contrat énergie",
    categoryId: "resiliation",
    description: "Mettre fin à un contrat d'électricité ou de gaz.",
    fields: [
      ...LETTER_BASE_FIELDS,
      { id: "point_livraison", label: "Point de livraison (PDL/PCE)", placeholder: "PDL 14 chiffres", required: true, section: "pieces" },
      { id: "date_effet", label: "Date d'effet souhaitée", placeholder: "31 mars 2026", required: true, section: "demande", type: "date" },
    ],
    subject: "Résiliation de mon contrat énergie",
    opening: "Madame, Monsieur,",
    toneEnabled: true,
    paragraphs: [
      { text: "{{tone_opening}} demander la résiliation de mon contrat d'énergie lié au point de livraison {{point_livraison}}." },
      { text: "Je souhaite que cette résiliation prenne effet le {{date_effet}}." },
      { text: "{{details}}", includeIf: "details" },
    ],
    closing: ["{{polite_formula}}"],
  },
  {
    id: "resil_compte_bancaire",
    version: "v1",
    title: "Clôture de compte bancaire",
    categoryId: "resiliation",
    description: "Demander la clôture d'un compte bancaire.",
    fields: [
      ...LETTER_BASE_FIELDS,
      { id: "iban_compte", label: "IBAN du compte à clôturer", placeholder: "FR76 ...", required: true, section: "pieces" },
      { id: "transfert_solde", label: "IBAN de transfert du solde", placeholder: "FR76 ...", required: false, section: "pieces" },
    ],
    subject: "Demande de clôture de compte bancaire",
    opening: "Madame, Monsieur,",
    toneEnabled: true,
    paragraphs: [
      { text: "{{tone_opening}} vous demander de clôturer le compte bancaire IBAN {{iban_compte}}." },
      { text: "Je vous remercie de transférer le solde disponible sur l'IBAN suivant : {{transfert_solde}}.", includeIf: "transfert_solde" },
      { text: "Merci de me confirmer par écrit la date effective de clôture.", },
      { text: "{{details}}", includeIf: "details" },
    ],
    closing: ["{{polite_formula}}"],
  },
  {
    id: "resil_abonnement_presse",
    version: "v1",
    title: "Résiliation abonnement presse",
    categoryId: "resiliation",
    description: "Mettre fin à un abonnement magazine/journal.",
    fields: [
      ...LETTER_BASE_FIELDS,
      { id: "reference_abonnement", label: "Référence abonnement", placeholder: "ABO-84572", required: true, section: "pieces" },
    ],
    subject: "Résiliation de mon abonnement presse",
    opening: "Madame, Monsieur,",
    toneEnabled: true,
    paragraphs: [
      { text: "{{tone_opening}} solliciter la résiliation de mon abonnement référencé {{reference_abonnement}}." },
      { text: "Je vous remercie de me confirmer la date d'arrêt et les conditions de remboursement éventuel.", },
      { text: "{{details}}", includeIf: "details" },
    ],
    closing: ["{{polite_formula}}"],
  },
  {
    id: "logt_demande_reparation",
    version: "v1",
    title: "Demande de réparation au bailleur",
    categoryId: "logement",
    description: "Signaler une réparation urgente ou nécessaire.",
    fields: [
      ...LETTER_BASE_FIELDS,
      { id: "adresse_logement", label: "Adresse du logement", placeholder: "12 rue X, 33000 Bordeaux", required: true, section: "demande" },
      { id: "probleme", label: "Problème constaté", placeholder: "Fuite d'eau cuisine", required: true, section: "demande", multiline: true, type: "textarea" },
    ],
    subject: "Demande de réparation dans le logement",
    opening: "Madame, Monsieur,",
    toneEnabled: true,
    paragraphs: [
      { text: "{{tone_opening}} signaler le problème suivant dans le logement situé {{adresse_logement}} : {{probleme}}." },
      { text: "Je vous remercie d'organiser une intervention dans les meilleurs délais.", },
      { text: "{{details}}", includeIf: "details" },
    ],
    closing: ["{{polite_formula}}"],
  },
  {
    id: "logt_contestation_charges",
    version: "v1",
    title: "Contestation de charges locatives",
    categoryId: "logement",
    description: "Contester une régularisation de charges.",
    fields: [
      ...LETTER_BASE_FIELDS,
      { id: "periode", label: "Période concernée", placeholder: "Exercice 2025", required: true, section: "pieces" },
      { id: "montant_conteste", label: "Montant contesté", placeholder: "184 EUR", required: true, section: "pieces" },
    ],
    subject: "Contestation de charges locatives",
    opening: "Madame, Monsieur,",
    toneEnabled: true,
    paragraphs: [
      { text: "{{tone_opening}} contester la régularisation de charges sur la période {{periode}} pour un montant de {{montant_conteste}}." },
      { text: "Je vous remercie de me communiquer les pièces justificatives correspondantes.", },
      { text: "{{details}}", includeIf: "details" },
    ],
    closing: ["{{polite_formula}}"],
  },
  {
    id: "logt_demande_quittance",
    version: "v1",
    title: "Demande de quittance de loyer",
    categoryId: "logement",
    description: "Demander l'envoi des quittances de loyer.",
    fields: [
      ...LETTER_BASE_FIELDS,
      { id: "periode", label: "Période demandée", placeholder: "janvier à mars 2026", required: true, section: "pieces" },
    ],
    subject: "Demande de quittance de loyer",
    opening: "Madame, Monsieur,",
    toneEnabled: true,
    paragraphs: [
      { text: "{{tone_opening}} me transmettre la ou les quittances de loyer pour la période {{periode}}." },
      { text: "{{details}}", includeIf: "details" },
    ],
    closing: ["{{polite_formula}}"],
  },
  {
    id: "rh_demande_formation",
    version: "v1",
    title: "Demande de formation professionnelle",
    categoryId: "travail",
    description: "Demander une formation en lien avec son poste.",
    fields: [
      ...LETTER_BASE_FIELDS,
      { id: "poste", label: "Poste actuel", placeholder: "Account manager", required: true, section: "demande" },
      { id: "formation", label: "Formation visée", placeholder: "Certification Google Ads", required: true, section: "demande" },
    ],
    subject: "Demande de formation professionnelle",
    opening: "Madame, Monsieur,",
    toneEnabled: true,
    paragraphs: [
      { text: "{{tone_opening}} solliciter la prise en charge de la formation suivante : {{formation}}." },
      { text: "Cette formation s'inscrit dans le développement de mes compétences sur le poste de {{poste}}." },
      { text: "{{details}}", includeIf: "details" },
    ],
    closing: ["{{polite_formula}}"],
  },
  {
    id: "rh_demande_augmentation",
    version: "v1",
    title: "Demande d'augmentation",
    categoryId: "travail",
    description: "Demander une revalorisation salariale argumentée.",
    fields: [
      ...LETTER_BASE_FIELDS,
      { id: "poste", label: "Poste actuel", placeholder: "Développeur front", required: true, section: "demande" },
      { id: "salaire_souhaite", label: "Salaire souhaité", placeholder: "48 000 EUR brut annuel", required: false, section: "pieces" },
    ],
    subject: "Demande de revalorisation salariale",
    opening: "Madame, Monsieur,",
    toneEnabled: true,
    paragraphs: [
      { text: "{{tone_opening}} solliciter une revalorisation de ma rémunération au titre de mes responsabilités sur le poste de {{poste}}." },
      { text: "Niveau de rémunération sollicité : {{salaire_souhaite}}.", includeIf: "salaire_souhaite" },
      { text: "{{details}}", includeIf: "details" },
    ],
    closing: ["{{polite_formula}}"],
  },
  {
    id: "rh_mutation_interne",
    version: "v1",
    title: "Demande de mutation interne",
    categoryId: "travail",
    description: "Demander un changement de site ou service.",
    fields: [
      ...LETTER_BASE_FIELDS,
      { id: "service_actuel", label: "Service actuel", placeholder: "Service production", required: true, section: "demande" },
      { id: "service_vise", label: "Service visé", placeholder: "Service qualité", required: true, section: "demande" },
    ],
    subject: "Demande de mutation interne",
    opening: "Madame, Monsieur,",
    toneEnabled: true,
    paragraphs: [
      { text: "{{tone_opening}} demander l'étude d'une mutation interne du service {{service_actuel}} vers le service {{service_vise}}." },
      { text: "{{details}}", includeIf: "details" },
    ],
    closing: ["{{polite_formula}}"],
  },
  {
    id: "adm_reclamation_generale",
    version: "v1",
    title: "Réclamation administrative générale",
    categoryId: "administratif",
    description: "Signaler un dysfonctionnement et demander traitement.",
    fields: [
      ...LETTER_BASE_FIELDS,
      { id: "objet_reclamation", label: "Objet de la réclamation", placeholder: "Retard de traitement dossier", required: true, section: "demande" },
      { id: "reference_dossier", label: "Référence dossier", placeholder: "DOS-2026-772", required: false, section: "pieces" },
    ],
    subject: "Réclamation - {{objet_reclamation}}",
    opening: "Madame, Monsieur,",
    toneEnabled: true,
    paragraphs: [
      { text: "{{tone_opening}} formuler une réclamation concernant : {{objet_reclamation}}." },
      { text: "Référence dossier : {{reference_dossier}}.", includeIf: "reference_dossier" },
      { text: "Je vous remercie de bien vouloir m'informer des suites données à ma demande.", },
      { text: "{{details}}", includeIf: "details" },
    ],
    closing: ["{{polite_formula}}"],
  },
  {
    id: "adm_changement_adresse",
    version: "v1",
    title: "Notification de changement d'adresse",
    categoryId: "administratif",
    description: "Informer un organisme de sa nouvelle adresse.",
    fields: [
      ...LETTER_BASE_FIELDS,
      { id: "ancienne_adresse", label: "Ancienne adresse", placeholder: "10 rue Y, 59000 Lille", required: true, section: "pieces" },
      { id: "nouvelle_adresse", label: "Nouvelle adresse", placeholder: "22 rue Z, 75011 Paris", required: true, section: "pieces" },
      { id: "date_effet", label: "Date d'effet", placeholder: "15 avril 2026", required: true, section: "demande", type: "date" },
    ],
    subject: "Changement d'adresse",
    opening: "Madame, Monsieur,",
    toneEnabled: false,
    paragraphs: [
      { text: "Je vous informe de mon changement d'adresse à compter du {{date_effet}}." },
      { text: "Ancienne adresse : {{ancienne_adresse}}." },
      { text: "Nouvelle adresse : {{nouvelle_adresse}}." },
      { text: "{{details}}", includeIf: "details" },
    ],
    closing: ["Je vous remercie d'actualiser mon dossier."],
  },
  {
    id: "adm_relance_dossier",
    version: "v1",
    title: "Relance de dossier en attente",
    categoryId: "administratif",
    description: "Relancer un dossier sans réponse.",
    fields: [
      ...LETTER_BASE_FIELDS,
      { id: "reference_dossier", label: "Référence dossier", placeholder: "DOS-2026-117", required: true, section: "pieces" },
      { id: "date_demande", label: "Date de la demande initiale", placeholder: "4 février 2026", required: true, section: "pieces", type: "date" },
    ],
    subject: "Relance dossier {{reference_dossier}}",
    opening: "Madame, Monsieur,",
    toneEnabled: true,
    paragraphs: [
      { text: "{{tone_opening}} relancer ma demande initiale transmise le {{date_demande}} sous la référence {{reference_dossier}}." },
      { text: "Je vous remercie de m'indiquer l'état d'avancement de ce dossier.", },
      { text: "{{details}}", includeIf: "details" },
    ],
    closing: ["{{polite_formula}}"],
  },
  {
    id: "jud_mise_en_demeure_travaux",
    version: "v1",
    title: "Mise en demeure d'exécuter des travaux",
    categoryId: "justice",
    description: "Exiger l'exécution de travaux contractuels.",
    fields: [
      ...LETTER_BASE_FIELDS,
      { id: "contrat_reference", label: "Référence contrat/devis", placeholder: "DEV-2026-981", required: true, section: "pieces" },
      { id: "delai", label: "Délai accordé (jours)", placeholder: "15", required: true, section: "demande", type: "number" },
    ],
    subject: "Mise en demeure d'exécuter les travaux convenus",
    opening: "Madame, Monsieur,",
    toneEnabled: true,
    paragraphs: [
      { text: "Le contrat référencé {{contrat_reference}} n'a pas été exécuté conformément aux engagements prévus." },
      { text: "Par la présente, {{tone_opening}} exécuter les travaux sous {{delai}} jours à compter de la réception du présent courrier." },
      { text: "À défaut, je me réserve la possibilité d'engager toute action utile.", },
      { text: "{{details}}", includeIf: "details" },
    ],
    closing: ["{{polite_formula}}"],
  },
  {
    id: "jud_resolution_contrat",
    version: "v1",
    title: "Demande de résolution de contrat",
    categoryId: "justice",
    description: "Demander la résolution d'un contrat non exécuté.",
    fields: [
      ...LETTER_BASE_FIELDS,
      { id: "contrat_reference", label: "Référence contrat", placeholder: "CTR-2026-445", required: true, section: "pieces" },
      { id: "motif", label: "Motif principal", placeholder: "Inexécution contractuelle persistante", required: true, section: "demande" },
    ],
    subject: "Demande de résolution du contrat {{contrat_reference}}",
    opening: "Madame, Monsieur,",
    toneEnabled: true,
    paragraphs: [
      { text: "{{tone_opening}} vous notifier ma demande de résolution du contrat {{contrat_reference}} pour le motif suivant : {{motif}}." },
      { text: "Je vous demande également la restitution des sommes indûment perçues le cas échéant.", },
      { text: "{{details}}", includeIf: "details" },
    ],
    closing: ["{{polite_formula}}"],
  },
  {
    id: "jud_non_conformite",
    version: "v1",
    title: "Signalement de non-conformité",
    categoryId: "justice",
    description: "Signaler un produit ou service non conforme.",
    fields: [
      ...LETTER_BASE_FIELDS,
      { id: "produit_service", label: "Produit / service concerné", placeholder: "Pompe à chaleur modèle X", required: true, section: "demande" },
      { id: "date_achat", label: "Date d'achat", placeholder: "2 mars 2026", required: false, section: "pieces", type: "date" },
    ],
    subject: "Signalement de non-conformité",
    opening: "Madame, Monsieur,",
    toneEnabled: true,
    paragraphs: [
      { text: "{{tone_opening}} signaler une non-conformité affectant {{produit_service}}." },
      { text: "Date d'achat ou de souscription : {{date_achat}}.", includeIf: "date_achat" },
      { text: "Je vous remercie de proposer une solution conforme dans les plus brefs délais.", },
      { text: "{{details}}", includeIf: "details" },
    ],
    closing: ["{{polite_formula}}"],
  },
  {
    id: "att_ressources",
    version: "v1",
    title: "Attestation de ressources",
    categoryId: "attestations",
    description: "Déclaration simple de niveau de ressources.",
    headerMode: "simple",
    toneEnabled: false,
    fields: [
      ...EXPEDITEUR_FIELDS,
      ...DATE_FIELDS,
      { id: "ressources", label: "Montant et nature des ressources", placeholder: "1 750 EUR mensuels - salaire", required: true, section: "demande", multiline: true, type: "textarea" },
    ],
    subject: "Attestation de ressources",
    paragraphs: [
      { text: "Je soussigné(e) {{expediteur_nom}} atteste percevoir les ressources suivantes :" },
      { text: "{{ressources}}" },
      { text: "La présente attestation est établie pour servir et valoir ce que de droit." },
    ],
    footer: ["Fait à {{lieu}}, le {{date}}.", "Signature : {{expediteur_nom}}"],
  },
  {
    id: "att_non_hebergement",
    version: "v1",
    title: "Attestation de non-hébergement",
    categoryId: "attestations",
    description: "Attester qu'une personne n'est pas hébergée à son domicile.",
    headerMode: "simple",
    toneEnabled: false,
    fields: [
      ...EXPEDITEUR_FIELDS,
      ...DATE_FIELDS,
      { id: "personne_concernee", label: "Personne concernée", placeholder: "Thomas Dubois", required: true, section: "demande" },
    ],
    subject: "Attestation de non-hébergement",
    paragraphs: [
      { text: "Je soussigné(e) {{expediteur_nom}} atteste que {{personne_concernee}} n'est pas hébergé(e) à mon domicile situé {{expediteur_adresse}}." },
      { text: "Cette déclaration est faite en toute bonne foi." },
    ],
    footer: ["Fait à {{lieu}}, le {{date}}.", "Signature : {{expediteur_nom}}"],
  },
  {
    id: "fam_autorisation_medicale",
    version: "v1",
    title: "Autorisation parentale soins médicaux",
    categoryId: "famille",
    description: "Autoriser un tiers à accompagner un mineur pour des soins.",
    headerMode: "simple",
    toneEnabled: false,
    fields: [
      ...EXPEDITEUR_FIELDS,
      ...DATE_FIELDS,
      DETAILS_FIELD,
      { id: "enfant_nom", label: "Nom de l'enfant", placeholder: "Noah Martin", required: true, section: "demande" },
      { id: "tiers_nom", label: "Nom du tiers autorisé", placeholder: "Camille Martin", required: true, section: "demande" },
      { id: "periode", label: "Période de validité", placeholder: "du 4 au 18 mai 2026", required: true, section: "pieces" },
    ],
    subject: "Autorisation parentale de soins",
    paragraphs: [
      { text: "Je soussigné(e) {{expediteur_nom}}, responsable légal(e) de {{enfant_nom}}, autorise {{tiers_nom}} à accompagner mon enfant et à effectuer les démarches nécessaires pour ses soins médicaux pendant {{periode}}." },
      { text: "Cette autorisation est donnée pour les situations courantes et urgentes." },
      { text: "{{details}}", includeIf: "details" },
    ],
    footer: ["Fait à {{lieu}}, le {{date}}.", "Signature : {{expediteur_nom}}"],
  },
  {
    id: "fam_accord_garde",
    version: "v1",
    title: "Accord amiable de garde",
    categoryId: "famille",
    description: "Formaliser un accord de garde alternée amiable.",
    headerMode: "simple",
    toneEnabled: false,
    fields: [
      ...EXPEDITEUR_FIELDS,
      ...DATE_FIELDS,
      DETAILS_FIELD,
      { id: "enfant_nom", label: "Nom de l'enfant", placeholder: "Lina Martin", required: true, section: "demande" },
      { id: "autre_parent", label: "Nom de l'autre parent", placeholder: "Sacha Martin", required: true, section: "demande" },
      { id: "organisation", label: "Organisation de garde", placeholder: "Une semaine sur deux", required: true, section: "demande", multiline: true, type: "textarea" },
    ],
    subject: "Accord amiable relatif à la garde de {{enfant_nom}}",
    paragraphs: [
      { text: "Le présent document formalise un accord amiable entre {{expediteur_nom}} et {{autre_parent}} concernant l'organisation de garde de {{enfant_nom}}." },
      { text: "Organisation convenue : {{organisation}}." },
      { text: "{{details}}", includeIf: "details" },
    ],
    footer: ["Fait à {{lieu}}, le {{date}}.", "Signature : {{expediteur_nom}}"],
  },
  {
    id: "rgpd_rectification",
    version: "v1",
    title: "Demande de rectification de données",
    categoryId: "numerique",
    description: "Corriger des données personnelles inexactes.",
    fields: [
      ...LETTER_BASE_FIELDS,
      { id: "service_concerne", label: "Service concerné", placeholder: "Espace client X", required: true, section: "pieces" },
      { id: "donnees_a_corriger", label: "Données à rectifier", placeholder: "Date de naissance / adresse", required: true, section: "demande", multiline: true, type: "textarea" },
    ],
    subject: "Exercice de mon droit de rectification",
    opening: "Madame, Monsieur,",
    toneEnabled: false,
    paragraphs: [
      { text: "Je vous demande de procéder à la rectification de mes données personnelles liées au service {{service_concerne}}." },
      { text: "Données concernées : {{donnees_a_corriger}}." },
      { text: "{{details}}", includeIf: "details" },
    ],
    closing: ["Je vous prie d'agréer, Madame, Monsieur, l'expression de mes salutations distinguées."],
  },
  {
    id: "rgpd_opposition",
    version: "v1",
    title: "Opposition au traitement marketing",
    categoryId: "numerique",
    description: "S'opposer aux sollicitations marketing.",
    fields: [
      ...LETTER_BASE_FIELDS,
      { id: "service_concerne", label: "Service concerné", placeholder: "Compte client X", required: true, section: "pieces" },
    ],
    subject: "Exercice de mon droit d'opposition",
    opening: "Madame, Monsieur,",
    toneEnabled: false,
    paragraphs: [
      { text: "Je vous notifie mon opposition à tout traitement de mes données personnelles à des fins de prospection commerciale concernant {{service_concerne}}." },
      { text: "Merci de confirmer la prise en compte de cette opposition.", },
      { text: "{{details}}", includeIf: "details" },
    ],
    closing: ["Je vous prie d'agréer, Madame, Monsieur, l'expression de mes salutations distinguées."],
  },
  {
    id: "rgpd_portabilite",
    version: "v1",
    title: "Demande de portabilité des données",
    categoryId: "numerique",
    description: "Obtenir ses données dans un format réutilisable.",
    fields: [
      ...LETTER_BASE_FIELDS,
      { id: "service_concerne", label: "Service concerné", placeholder: "Application X", required: true, section: "pieces" },
      { id: "format_souhaite", label: "Format souhaité", placeholder: "CSV ou JSON", required: false, section: "pieces" },
    ],
    subject: "Exercice de mon droit à la portabilité",
    opening: "Madame, Monsieur,",
    toneEnabled: false,
    paragraphs: [
      { text: "Je vous demande de me transmettre les données personnelles me concernant, relatives au service {{service_concerne}}, dans un format structuré et réutilisable." },
      { text: "Format souhaité : {{format_souhaite}}.", includeIf: "format_souhaite" },
      { text: "{{details}}", includeIf: "details" },
    ],
    closing: ["Je vous prie d'agréer, Madame, Monsieur, l'expression de mes salutations distinguées."],
  },
  {
    id: "rh_lettre_motivation",
    version: "v1",
    title: "Lettre de motivation",
    categoryId: "travail",
    description: "Candidature motivee pour poste salarie.",
    fields: [
      ...LETTER_BASE_FIELDS,
      { id: "poste_vise", label: "Poste visé", placeholder: "Chef de projet digital", required: true, section: "demande" },
      { id: "entreprise_visee", label: "Entreprise visée", placeholder: "Entreprise ABC", required: true, section: "demande" },
      { id: "atouts", label: "Atouts principaux", placeholder: "Gestion de projets complexes, coordination transverse...", required: true, section: "demande", multiline: true, type: "textarea" },
    ],
    subject: "Candidature au poste de {{poste_vise}}",
    opening: "Madame, Monsieur,",
    toneEnabled: true,
    paragraphs: [
      { text: "{{tone_opening}} vous proposer ma candidature au poste de {{poste_vise}} au sein de {{entreprise_visee}}." },
      { text: "Mes principaux atouts pour ce poste sont les suivants : {{atouts}}." },
      { text: "Je serais ravi(e) d'échanger avec vous lors d'un entretien.", },
      { text: "{{details}}", includeIf: "details" },
    ],
    closing: ["{{polite_formula}}"],
  },
  {
    id: "rh_candidature_spontanee",
    version: "v1",
    title: "Candidature spontanée",
    categoryId: "travail",
    description: "Proposer sa candidature hors offre publiee.",
    fields: [
      ...LETTER_BASE_FIELDS,
      { id: "entreprise_visee", label: "Entreprise visée", placeholder: "Entreprise XYZ", required: true, section: "demande" },
      { id: "metier", label: "Métier / fonction ciblée", placeholder: "Data analyst", required: true, section: "demande" },
      { id: "profil_resume", label: "Résumé du profil", placeholder: "5 ans d'expérience en analyse de données...", required: true, section: "demande", multiline: true, type: "textarea" },
    ],
    subject: "Candidature spontanée - {{metier}}",
    opening: "Madame, Monsieur,",
    toneEnabled: true,
    paragraphs: [
      { text: "{{tone_opening}} vous adresser ma candidature spontanée pour des opportunités en {{metier}} au sein de {{entreprise_visee}}." },
      { text: "Mon profil en bref : {{profil_resume}}." },
      { text: "{{details}}", includeIf: "details" },
    ],
    closing: ["{{polite_formula}}"],
  },
  {
    id: "rh_demande_stage",
    version: "v1",
    title: "Demande de stage",
    categoryId: "travail",
    description: "Candidature pour stage conventionne.",
    fields: [
      ...LETTER_BASE_FIELDS,
      { id: "domaine", label: "Domaine du stage", placeholder: "Développement web", required: true, section: "demande" },
      { id: "periode_stage", label: "Période souhaitée", placeholder: "de mai à juillet 2026", required: true, section: "pieces" },
      { id: "ecole", label: "Établissement", placeholder: "Université de Lyon", required: true, section: "pieces" },
    ],
    subject: "Demande de stage - {{domaine}}",
    opening: "Madame, Monsieur,",
    toneEnabled: true,
    paragraphs: [
      { text: "{{tone_opening}} solliciter un stage dans le domaine {{domaine}} pour la période {{periode_stage}}." },
      { text: "Ce stage s'inscrit dans le cadre de ma formation à {{ecole}}." },
      { text: "{{details}}", includeIf: "details" },
    ],
    closing: ["{{polite_formula}}"],
  },
  {
    id: "fin_contestation_prelevement",
    version: "v1",
    title: "Contestation de prélèvement",
    categoryId: "finance",
    description: "Contester un prélèvement bancaire non autorisé.",
    fields: [
      ...LETTER_BASE_FIELDS,
      { id: "date_operation", label: "Date de l'opération", placeholder: "12 mars 2026", required: true, section: "pieces", type: "date" },
      { id: "montant", label: "Montant", placeholder: "89 EUR", required: true, section: "pieces" },
      { id: "libelle", label: "Libellé de l'opération", placeholder: "PRLV XYZ", required: true, section: "pieces" },
    ],
    subject: "Contestation de prélèvement bancaire",
    opening: "Madame, Monsieur,",
    toneEnabled: true,
    paragraphs: [
      { text: "{{tone_opening}} contester l'opération du {{date_operation}} d'un montant de {{montant}} libellée {{libelle}}." },
      { text: "Je vous remercie de procéder aux vérifications nécessaires et d'engager la régularisation appropriée." },
      { text: "{{details}}", includeIf: "details" },
    ],
    closing: ["{{polite_formula}}"],
  },
  {
    id: "fin_demande_opposition_carte",
    version: "v1",
    title: "Demande d'opposition carte bancaire",
    categoryId: "finance",
    description: "Demander l'opposition immédiate d'une carte.",
    fields: [
      ...LETTER_BASE_FIELDS,
      { id: "numero_partiel", label: "4 derniers chiffres carte", placeholder: "4521", required: true, section: "pieces" },
      { id: "motif", label: "Motif", placeholder: "Perte / vol / usage frauduleux", required: true, section: "demande" },
    ],
    subject: "Demande d'opposition de carte bancaire",
    opening: "Madame, Monsieur,",
    toneEnabled: true,
    paragraphs: [
      { text: "{{tone_opening}} procéder immédiatement à l'opposition de ma carte se terminant par {{numero_partiel}}, motif : {{motif}}." },
      { text: "Merci de me confirmer la prise en compte de cette opposition et les suites à donner." },
      { text: "{{details}}", includeIf: "details" },
    ],
    closing: ["{{polite_formula}}"],
  },
  {
    id: "fin_demande_echeancier_banque",
    version: "v1",
    title: "Demande d'échéancier bancaire",
    categoryId: "finance",
    description: "Négocier un échéancier sur une dette bancaire.",
    fields: [
      ...LETTER_BASE_FIELDS,
      { id: "montant", label: "Montant concerné", placeholder: "2 400 EUR", required: true, section: "pieces" },
      { id: "proposition", label: "Proposition d'échéancier", placeholder: "6 mensualités de 400 EUR", required: true, section: "demande" },
    ],
    subject: "Demande d'échéancier de paiement",
    opening: "Madame, Monsieur,",
    toneEnabled: true,
    paragraphs: [
      { text: "{{tone_opening}} solliciter un échéancier sur la somme de {{montant}}." },
      { text: "Je propose le plan suivant : {{proposition}}." },
      { text: "{{details}}", includeIf: "details" },
    ],
    closing: ["{{polite_formula}}"],
  },
  {
    id: "fin_demande_releve_operation",
    version: "v1",
    title: "Demande de relevé d'opérations",
    categoryId: "finance",
    description: "Demander un relevé détaillé des opérations.",
    fields: [
      ...LETTER_BASE_FIELDS,
      { id: "periode", label: "Période demandée", placeholder: "janvier a mars 2026", required: true, section: "pieces" },
      { id: "compte_ref", label: "Référence compte", placeholder: "FR76 ...", required: false, section: "pieces" },
    ],
    subject: "Demande de relevé d'opérations",
    opening: "Madame, Monsieur,",
    toneEnabled: false,
    paragraphs: [
      { text: "Je vous remercie de me transmettre le relevé détaillé de mes opérations pour la période {{periode}}." },
      { text: "Compte concerné : {{compte_ref}}.", includeIf: "compte_ref" },
      { text: "{{details}}", includeIf: "details" },
    ],
    closing: ["Je vous prie d'agréer, Madame, Monsieur, l'expression de mes salutations distinguées."],
  },
  {
    id: "fin_resiliation_assurance_vie",
    version: "v1",
    title: "Résiliation assurance vie",
    categoryId: "finance",
    description: "Demander la clôture d'un contrat d'assurance vie.",
    fields: [
      ...LETTER_BASE_FIELDS,
      { id: "numero_contrat", label: "Numéro de contrat", placeholder: "AV-99384", required: true, section: "pieces" },
      { id: "mode_sortie", label: "Mode de sortie", placeholder: "Rachat total", required: true, section: "demande" },
    ],
    subject: "Demande de clôture assurance vie",
    opening: "Madame, Monsieur,",
    toneEnabled: true,
    paragraphs: [
      { text: "{{tone_opening}} demander le {{mode_sortie}} du contrat d'assurance vie n° {{numero_contrat}}." },
      { text: "Merci de m'indiquer les pièces et délais associés au traitement de cette demande." },
      { text: "{{details}}", includeIf: "details" },
    ],
    closing: ["{{polite_formula}}"],
  },
  {
    id: "fin_demande_attestation_assurance",
    version: "v1",
    title: "Demande d'attestation d'assurance",
    categoryId: "finance",
    description: "Obtenir une attestation d'assurance.",
    fields: [
      ...LETTER_BASE_FIELDS,
      { id: "type_contrat", label: "Type de contrat", placeholder: "Habitation", required: true, section: "pieces" },
      { id: "numero_contrat", label: "Numéro de contrat", placeholder: "HAB-2237", required: true, section: "pieces" },
    ],
    subject: "Demande d'attestation d'assurance",
    opening: "Madame, Monsieur,",
    toneEnabled: false,
    paragraphs: [
      { text: "Je vous remercie de me faire parvenir une attestation d'assurance pour mon contrat {{type_contrat}} n° {{numero_contrat}}." },
      { text: "{{details}}", includeIf: "details" },
    ],
    closing: ["Je vous prie d'agréer, Madame, Monsieur, l'expression de mes salutations distinguées."],
  },
  {
    id: "mob_contestation_amende_stationnement",
    version: "v1",
    title: "Contestation amende stationnement",
    categoryId: "mobilite",
    description: "Contester une contravention de stationnement.",
    fields: [
      ...LETTER_BASE_FIELDS,
      { id: "numero_amende", label: "Numéro d'amende", placeholder: "FPS-2026-0091", required: true, section: "pieces" },
      { id: "immatriculation", label: "Immatriculation", placeholder: "AB-123-CD", required: true, section: "pieces" },
    ],
    subject: "Contestation de forfait post-stationnement",
    opening: "Madame, Monsieur,",
    toneEnabled: true,
    paragraphs: [
      { text: "{{tone_opening}} contester l'avis de paiement n° {{numero_amende}} relatif au véhicule {{immatriculation}}." },
      { text: "Je vous remercie de réexaminer ce dossier et de m'informer de votre décision." },
      { text: "{{details}}", includeIf: "details" },
    ],
    closing: ["{{polite_formula}}"],
  },
  {
    id: "mob_reclamation_transport",
    version: "v1",
    title: "Réclamation transport public",
    categoryId: "mobilite",
    description: "Réclamer suite à incident dans les transports.",
    fields: [
      ...LETTER_BASE_FIELDS,
      { id: "ligne", label: "Ligne / trajet", placeholder: "Ligne 1 - Chatelet > Nation", required: true, section: "pieces" },
      { id: "date_incident", label: "Date de l'incident", placeholder: "8 avril 2026", required: true, section: "pieces", type: "date" },
    ],
    subject: "Réclamation concernant un incident de transport",
    opening: "Madame, Monsieur,",
    toneEnabled: true,
    paragraphs: [
      { text: "{{tone_opening}} formuler une réclamation concernant l'incident survenu le {{date_incident}} sur {{ligne}}." },
      { text: "Je sollicite l'étude de ma demande et une réponse motivée." },
      { text: "{{details}}", includeIf: "details" },
    ],
    closing: ["{{polite_formula}}"],
  },
  {
    id: "mob_demande_remboursement_pass",
    version: "v1",
    title: "Demande remboursement abonnement transport",
    categoryId: "mobilite",
    description: "Demander remboursement d'un pass transport.",
    fields: [
      ...LETTER_BASE_FIELDS,
      { id: "numero_abonnement", label: "Numéro d'abonnement", placeholder: "PASS-28471", required: true, section: "pieces" },
      { id: "motif", label: "Motif", placeholder: "Abonnement inutilisable suite à panne", required: true, section: "demande" },
      { id: "montant", label: "Montant demandé", placeholder: "49 EUR", required: true, section: "pieces" },
    ],
    subject: "Demande de remboursement d'abonnement transport",
    opening: "Madame, Monsieur,",
    toneEnabled: true,
    paragraphs: [
      { text: "{{tone_opening}} demander le remboursement de mon abonnement n° {{numero_abonnement}} pour un montant de {{montant}}." },
      { text: "Motif : {{motif}}." },
      { text: "{{details}}", includeIf: "details" },
    ],
    closing: ["{{polite_formula}}"],
  },
  {
    id: "mob_demande_macaron_resident",
    version: "v1",
    title: "Demande macaron résident",
    categoryId: "mobilite",
    description: "Demander un droit de stationnement résident.",
    fields: [
      ...LETTER_BASE_FIELDS,
      { id: "immatriculation", label: "Immatriculation", placeholder: "AB-123-CD", required: true, section: "pieces" },
      { id: "adresse_residence", label: "Adresse de résidence", placeholder: "12 rue X, 75011 Paris", required: true, section: "pieces" },
    ],
    subject: "Demande de stationnement résident",
    opening: "Madame, Monsieur,",
    toneEnabled: false,
    paragraphs: [
      { text: "Je souhaite bénéficier du dispositif de stationnement résident pour le véhicule immatriculé {{immatriculation}}." },
      { text: "Adresse de résidence : {{adresse_residence}}." },
      { text: "{{details}}", includeIf: "details" },
    ],
    closing: ["Je vous prie d'agréer, Madame, Monsieur, l'expression de mes salutations distinguées."],
  },
  {
    id: "mob_demande_duplication_carte_grise",
    version: "v1",
    title: "Demande duplicata carte grise",
    categoryId: "mobilite",
    description: "Demander un duplicata de certificat d'immatriculation.",
    fields: [
      ...LETTER_BASE_FIELDS,
      { id: "immatriculation", label: "Immatriculation", placeholder: "AB-123-CD", required: true, section: "pieces" },
      { id: "motif", label: "Motif", placeholder: "Perte / vol / détérioration", required: true, section: "demande" },
    ],
    subject: "Demande de duplicata du certificat d'immatriculation",
    opening: "Madame, Monsieur,",
    toneEnabled: false,
    paragraphs: [
      { text: "Je sollicite l'établissement d'un duplicata de certificat d'immatriculation pour le véhicule {{immatriculation}}." },
      { text: "Motif de la demande : {{motif}}." },
      { text: "{{details}}", includeIf: "details" },
    ],
    closing: ["Je vous prie d'agréer, Madame, Monsieur, l'expression de mes salutations distinguées."],
  },
  {
    id: "mob_declaration_sinistre_auto",
    version: "v1",
    title: "Déclaration de sinistre auto",
    categoryId: "mobilite",
    description: "Déclarer un sinistre automobile à l'assureur.",
    fields: [
      ...LETTER_BASE_FIELDS,
      { id: "numero_contrat", label: "Numéro de contrat auto", placeholder: "AUTO-77812", required: true, section: "pieces" },
      { id: "date_sinistre", label: "Date du sinistre", placeholder: "2 mai 2026", required: true, section: "pieces", type: "date" },
      { id: "immatriculation", label: "Immatriculation", placeholder: "AB-123-CD", required: true, section: "pieces" },
    ],
    subject: "Déclaration de sinistre automobile",
    opening: "Madame, Monsieur,",
    toneEnabled: true,
    paragraphs: [
      { text: "{{tone_opening}} déclarer un sinistre survenu le {{date_sinistre}} concernant le véhicule {{immatriculation}}, rattaché au contrat {{numero_contrat}}." },
      { text: "Je vous remercie de m'indiquer les étapes de prise en charge de ce dossier." },
      { text: "{{details}}", includeIf: "details" },
    ],
    closing: ["{{polite_formula}}"],
  },
];

export function getV1Categories(): DocumentCategory[] {
  return CATEGORIES_V1;
}

export function getV1Templates(): DocumentTemplate[] {
  return [...TEMPLATES_V1, ...EXTRA_TEMPLATES_V1];
}
